name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: push to droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - run: echo "key    ${{ secrets.PRIVATE_SSH_KEY }}""

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 64.227.165.59
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: whoami
